DOCKER_IMAGE_NAME=$(PYTHON_PKG_NAME)
PYTHON_BOOT_MODULE ?= $(PYTHON_PKG_WORKDIR)/runtime/boot.py
PYTHON_PKG_WORKDIR ?= $(PYTHON_PKG_NAME)
PYTHON_SETTINGS_PKG = $(PYTHON_PKG_WORKDIR)/runtime/settings
PYTHON_SETUPTOOLS_PKG_FINDER=find_packages
PYTHON_QUALNAME ?= $(PYTHON_PKG_NAME)
PYPI_METADATA_FILE ?= $(PYTHON_PKG_NAME)/package.json


configure-python-parent:
